/**
 * Writes drizzle/0002_starter_content.sql from src/server/seed-content.ts.
 *
 * The starter content ships as a database migration so it loads automatically on the first
 * deploy (Netlify applies migrations itself). Every insert is ON CONFLICT DO NOTHING.
 * Content is published with no review date, so the site shows "Awaiting clinical review".
 *
 * Run: npx tsx scripts/build-starter-sql.ts && npx tsx scripts/sync-migrations.ts
 */
import { writeFileSync } from 'node:fs';
import path from 'node:path';
import { seedArticles, seedCategories, seedFaqs } from '../src/server/seed-content';

const TAG = '$perio$';
function lit(value: string | null | undefined): string {
  if (value === null || value === undefined) return 'NULL';
  if (value.includes(TAG)) throw new Error(`Content contains ${TAG}`);
  return `${TAG}${value}${TAG}`;
}
const arr = (items: string[]) => (items.length ? `ARRAY[${items.map(lit).join(', ')}]::text[]` : `'{}'::text[]`);
const cat = (slug: string) => `(SELECT id FROM categories WHERE slug = ${lit(slug)})`;

const out: string[] = [
  '-- Starter content for the knowledge hub. Generated by scripts/build-starter-sql.ts: edit',
  '-- src/server/seed-content.ts and regenerate rather than editing this file by hand.',
  '-- Drafts written to show how the hub works; published but NOT clinically reviewed.',
  '',
];

seedCategories.forEach((c, i) => {
  out.push(
    `INSERT INTO categories (slug, name, description, sort_order) VALUES (${lit(c.slug)}, ${lit(c.name)}, ${lit(c.description)}, ${(i + 1) * 10}) ON CONFLICT (slug) DO NOTHING;`,
  );
});
out.push('');

for (const f of seedFaqs) {
  out.push(
    `INSERT INTO faqs (slug, audience, question, summary, answer, "references", tags, status, category_id, published_at) VALUES (${lit(f.slug)}, '${f.audience}', ${lit(f.question)}, ${lit(f.summary)}, ${lit(f.answer)}, ${lit(f.references)}, ${arr(f.tags)}, 'PUBLISHED', ${cat(f.category)}, now()) ON CONFLICT (slug) DO NOTHING;`,
    '',
  );
}

for (const a of seedArticles) {
  out.push(
    `INSERT INTO articles (slug, audience, title, summary, body, members_only, tags, status, category_id, published_at) VALUES (${lit(a.slug)}, '${a.audience}', ${lit(a.title)}, ${lit(a.summary)}, ${lit(a.body)}, ${a.membersOnly}, ${arr(a.tags)}, 'PUBLISHED', ${cat(a.category)}, now()) ON CONFLICT (slug) DO NOTHING;`,
    '',
  );
}

const file = path.resolve(__dirname, '../drizzle/0002_starter_content.sql');
writeFileSync(file, out.join('\n'));
console.log(`Wrote ${file}: ${seedCategories.length} topics, ${seedFaqs.length} FAQs, ${seedArticles.length} articles`);
